name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file docker_build/Dockerfile --tag moodle-docker-php:8.4-fpm
    - name: push the Docker image
      run: docker push ghcr.io/tsmu-hub/moodle-docker-php:latest
