name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker_build/Dockerfile --tag php-moodle:8.4-fpm-moodle
    - name: push the Docker image
      run: docker push ghcr.io/tsmu-hub/moodle-docker-php:latest
